[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd tyva-transit-backend && python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
