# Generated by Django 6.0.6 on 2026-06-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('route_label', models.CharField(help_text='Например: Кызыл → Чагытай', max_length=200, verbose_name='Маршрут')),
                ('meeting_point', models.CharField(default='ул. Кочетова, 2', max_length=300, verbose_name='Сбор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['route_label'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_at', models.DateTimeField(verbose_name='Выезд')),
                ('seats_total', models.PositiveSmallIntegerField(default=12, verbose_name='Мест всего')),
                ('seats_booked', models.PositiveSmallIntegerField(default=0, verbose_name='Забронировано')),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за место')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Часов в пути')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transit.destination')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['departure_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('booking_type', models.CharField(choices=[('shared', 'Общий рейс'), ('private', 'Личная поездка')], max_length=10, verbose_name='Тип')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачено'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=12, verbose_name='Статус')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата выезда')),
                ('departure_time', models.CharField(blank=True, max_length=80, verbose_name='Время')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата обратно')),
                ('round_trip', models.BooleanField(default=False, verbose_name='Туда-обратно')),
                ('vehicle_type', models.CharField(blank=True, choices=[('minivan_8', 'Минивэн до 8 мест'), ('bus_12', 'Микроавтобус до 12 мест')], max_length=20, verbose_name='Машина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('seats', models.PositiveSmallIntegerField(default=1, verbose_name='Мест')),
                ('payment_method', models.CharField(choices=[('sbp', 'СБП'), ('card', 'Банковская карта'), ('stub', 'Заглушка')], default='stub', max_length=10, verbose_name='Оплата')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Билет отправлен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='transit.destination')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='transit.trip')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-created_at'],
            },
        ),
    ]
